// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvj35QuPlEWUkOA8J7y6nhnn3tPo_tbgk',
    appId: '1:62948653790:web:c9ea693544f45ad0b0604f',
    messagingSenderId: '62948653790',
    projectId: 'flutterlogin-db068',
    authDomain: 'flutterlogin-db068.firebaseapp.com',
    storageBucket: 'flutterlogin-db068.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4-kuYy6YxZ-yhWXajGcTSuXaq11CjBxk',
    appId: '1:62948653790:android:9259175a354195b4b0604f',
    messagingSenderId: '62948653790',
    projectId: 'flutterlogin-db068',
    storageBucket: 'flutterlogin-db068.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOuN3LPtqEz63DZCEUomyEkjQp3vktSpg',
    appId: '1:62948653790:ios:a6c4f20dae529e13b0604f',
    messagingSenderId: '62948653790',
    projectId: 'flutterlogin-db068',
    storageBucket: 'flutterlogin-db068.appspot.com',
    iosClientId: '62948653790-hdtua4e80om72mj161fuic7qhg3u6ars.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloNeighbour',
  );
}
